<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '"{number}" is not a valid card number' => '"{number}" não é um número de cartão válido.',
    '"{value}" does not seem to be a valid phone number.' => '"{value}" não parece ser um número de telefone válido.',
    'A maximum of {value, number} {value, plural, one{email is} other{emails are}} allowed.' => 'Um máximo de {value, number} {value, plural, um{email is} outros{emails are}} permitido.',
    'At least {value, number} {value, plural, one{email is} other{emails are}} required.' => 'Pelo menos {value, number} {value, plural, um{email is} outros{emails are}} requeridos.',
    'Country is required for phone validation.' => 'Páis é requerido para validação de telefone.',
    'Invalid CVV "{cvv}"' => 'CVV Inválido',
    'Invalid expiry month/year "{expiry}"' => 'Mês/Ano de expiração é inválido.',
    'Invalid holder name "{holder}"' => 'Nome do portador do cartão inválido.',
    'Unsupported card number "{number}"' => 'Número de cartão não suportado.',
    '"{value}" is not a valid email address.' => '',
    'Invalid JSON input for "{attribute}". {exception}' => '',
    'Unexpected or unrecognized phone number format.' => '',
];
