<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '"{number}" is not a valid card number' => '',
    '"{value}" does not seem to be a valid phone number.' => '',
    '"{value}" is not a valid email address.' => '',
    'A maximum of {value, number} {value, plural, one{email is} other{emails are}} allowed.' => '',
    'At least {value, number} {value, plural, one{email is} other{emails are}} required.' => '',
    'Country is required for phone validation.' => '',
    'Invalid CVV "{cvv}"' => '',
    'Invalid JSON input for "{attribute}". {exception}' => '',
    'Invalid expiry month/year "{expiry}"' => '',
    'Invalid holder name "{holder}"' => '',
    'Unexpected or unrecognized phone number format.' => '',
    'Unsupported card number "{number}"' => '',
];
